/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Sensor extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4017640418909675822L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Sensor\",\"namespace\":\"com.example\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"internalTemperature\",\"type\":\"float\",\"default\":0.0,\"aliases\":[\"temperature\"]},{\"name\":\"externalTemperature\",\"type\":\"float\",\"default\":0.0},{\"name\":\"acceleration\",\"type\":\"float\",\"default\":0.0},{\"name\":\"velocity\",\"type\":\"float\",\"default\":0.0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Sensor> ENCODER =
      new BinaryMessageEncoder<Sensor>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Sensor> DECODER =
      new BinaryMessageDecoder<Sensor>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Sensor> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Sensor> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Sensor>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Sensor to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Sensor from a ByteBuffer. */
  public static Sensor fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String id;
  @Deprecated public float internalTemperature;
  @Deprecated public float externalTemperature;
  @Deprecated public float acceleration;
  @Deprecated public float velocity;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Sensor() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param internalTemperature The new value for internalTemperature
   * @param externalTemperature The new value for externalTemperature
   * @param acceleration The new value for acceleration
   * @param velocity The new value for velocity
   */
  public Sensor(java.lang.String id, java.lang.Float internalTemperature, java.lang.Float externalTemperature, java.lang.Float acceleration, java.lang.Float velocity) {
    this.id = id;
    this.internalTemperature = internalTemperature;
    this.externalTemperature = externalTemperature;
    this.acceleration = acceleration;
    this.velocity = velocity;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return internalTemperature;
    case 2: return externalTemperature;
    case 3: return acceleration;
    case 4: return velocity;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.String)value$; break;
    case 1: internalTemperature = (java.lang.Float)value$; break;
    case 2: externalTemperature = (java.lang.Float)value$; break;
    case 3: acceleration = (java.lang.Float)value$; break;
    case 4: velocity = (java.lang.Float)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'internalTemperature' field.
   * @return The value of the 'internalTemperature' field.
   */
  public java.lang.Float getInternalTemperature() {
    return internalTemperature;
  }

  /**
   * Sets the value of the 'internalTemperature' field.
   * @param value the value to set.
   */
  public void setInternalTemperature(java.lang.Float value) {
    this.internalTemperature = value;
  }

  /**
   * Gets the value of the 'externalTemperature' field.
   * @return The value of the 'externalTemperature' field.
   */
  public java.lang.Float getExternalTemperature() {
    return externalTemperature;
  }

  /**
   * Sets the value of the 'externalTemperature' field.
   * @param value the value to set.
   */
  public void setExternalTemperature(java.lang.Float value) {
    this.externalTemperature = value;
  }

  /**
   * Gets the value of the 'acceleration' field.
   * @return The value of the 'acceleration' field.
   */
  public java.lang.Float getAcceleration() {
    return acceleration;
  }

  /**
   * Sets the value of the 'acceleration' field.
   * @param value the value to set.
   */
  public void setAcceleration(java.lang.Float value) {
    this.acceleration = value;
  }

  /**
   * Gets the value of the 'velocity' field.
   * @return The value of the 'velocity' field.
   */
  public java.lang.Float getVelocity() {
    return velocity;
  }

  /**
   * Sets the value of the 'velocity' field.
   * @param value the value to set.
   */
  public void setVelocity(java.lang.Float value) {
    this.velocity = value;
  }

  /**
   * Creates a new Sensor RecordBuilder.
   * @return A new Sensor RecordBuilder
   */
  public static com.example.Sensor.Builder newBuilder() {
    return new com.example.Sensor.Builder();
  }

  /**
   * Creates a new Sensor RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Sensor RecordBuilder
   */
  public static com.example.Sensor.Builder newBuilder(com.example.Sensor.Builder other) {
    return new com.example.Sensor.Builder(other);
  }

  /**
   * Creates a new Sensor RecordBuilder by copying an existing Sensor instance.
   * @param other The existing instance to copy.
   * @return A new Sensor RecordBuilder
   */
  public static com.example.Sensor.Builder newBuilder(com.example.Sensor other) {
    return new com.example.Sensor.Builder(other);
  }

  /**
   * RecordBuilder for Sensor instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Sensor>
    implements org.apache.avro.data.RecordBuilder<Sensor> {

    private java.lang.String id;
    private float internalTemperature;
    private float externalTemperature;
    private float acceleration;
    private float velocity;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.Sensor.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.internalTemperature)) {
        this.internalTemperature = data().deepCopy(fields()[1].schema(), other.internalTemperature);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.externalTemperature)) {
        this.externalTemperature = data().deepCopy(fields()[2].schema(), other.externalTemperature);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.acceleration)) {
        this.acceleration = data().deepCopy(fields()[3].schema(), other.acceleration);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.velocity)) {
        this.velocity = data().deepCopy(fields()[4].schema(), other.velocity);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Sensor instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.Sensor other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.internalTemperature)) {
        this.internalTemperature = data().deepCopy(fields()[1].schema(), other.internalTemperature);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.externalTemperature)) {
        this.externalTemperature = data().deepCopy(fields()[2].schema(), other.externalTemperature);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.acceleration)) {
        this.acceleration = data().deepCopy(fields()[3].schema(), other.acceleration);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.velocity)) {
        this.velocity = data().deepCopy(fields()[4].schema(), other.velocity);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.example.Sensor.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.example.Sensor.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'internalTemperature' field.
      * @return The value.
      */
    public java.lang.Float getInternalTemperature() {
      return internalTemperature;
    }

    /**
      * Sets the value of the 'internalTemperature' field.
      * @param value The value of 'internalTemperature'.
      * @return This builder.
      */
    public com.example.Sensor.Builder setInternalTemperature(float value) {
      validate(fields()[1], value);
      this.internalTemperature = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'internalTemperature' field has been set.
      * @return True if the 'internalTemperature' field has been set, false otherwise.
      */
    public boolean hasInternalTemperature() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'internalTemperature' field.
      * @return This builder.
      */
    public com.example.Sensor.Builder clearInternalTemperature() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'externalTemperature' field.
      * @return The value.
      */
    public java.lang.Float getExternalTemperature() {
      return externalTemperature;
    }

    /**
      * Sets the value of the 'externalTemperature' field.
      * @param value The value of 'externalTemperature'.
      * @return This builder.
      */
    public com.example.Sensor.Builder setExternalTemperature(float value) {
      validate(fields()[2], value);
      this.externalTemperature = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'externalTemperature' field has been set.
      * @return True if the 'externalTemperature' field has been set, false otherwise.
      */
    public boolean hasExternalTemperature() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'externalTemperature' field.
      * @return This builder.
      */
    public com.example.Sensor.Builder clearExternalTemperature() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'acceleration' field.
      * @return The value.
      */
    public java.lang.Float getAcceleration() {
      return acceleration;
    }

    /**
      * Sets the value of the 'acceleration' field.
      * @param value The value of 'acceleration'.
      * @return This builder.
      */
    public com.example.Sensor.Builder setAcceleration(float value) {
      validate(fields()[3], value);
      this.acceleration = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'acceleration' field has been set.
      * @return True if the 'acceleration' field has been set, false otherwise.
      */
    public boolean hasAcceleration() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'acceleration' field.
      * @return This builder.
      */
    public com.example.Sensor.Builder clearAcceleration() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'velocity' field.
      * @return The value.
      */
    public java.lang.Float getVelocity() {
      return velocity;
    }

    /**
      * Sets the value of the 'velocity' field.
      * @param value The value of 'velocity'.
      * @return This builder.
      */
    public com.example.Sensor.Builder setVelocity(float value) {
      validate(fields()[4], value);
      this.velocity = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'velocity' field has been set.
      * @return True if the 'velocity' field has been set, false otherwise.
      */
    public boolean hasVelocity() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'velocity' field.
      * @return This builder.
      */
    public com.example.Sensor.Builder clearVelocity() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Sensor build() {
      try {
        Sensor record = new Sensor();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.internalTemperature = fieldSetFlags()[1] ? this.internalTemperature : (java.lang.Float) defaultValue(fields()[1]);
        record.externalTemperature = fieldSetFlags()[2] ? this.externalTemperature : (java.lang.Float) defaultValue(fields()[2]);
        record.acceleration = fieldSetFlags()[3] ? this.acceleration : (java.lang.Float) defaultValue(fields()[3]);
        record.velocity = fieldSetFlags()[4] ? this.velocity : (java.lang.Float) defaultValue(fields()[4]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Sensor>
    WRITER$ = (org.apache.avro.io.DatumWriter<Sensor>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Sensor>
    READER$ = (org.apache.avro.io.DatumReader<Sensor>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
